### ISSUE TITLE
Application Cache is deprecated?

### ISSUE THREAD

**Issue by wouterbeek** [TriplyDB/Yasgui#107]
On http://yasgui.org I see the following message in the Chrome developer console:

> Use of the Application Cache is deprecated on insecure origins. Support will be removed in the future. You should consider switching your application to a secure origin, such as HTTPS. See https://goo.gl/rStTGz for more details.

Is this something we should worry about?

**Comment by LaurensRietveld** [comment]
Not really, we'd loose the ability to view yasgui offline, but it's not critical, and would still work for https

**Comment by wouterbeek** [comment]
Yes, apparently this is an HTTP-specific issue.  While I agree that losing offline functionality is not critical, I do consider it to be an important feature.  (Maybe we can leave this issue open in case somebody else wants to take a look into this.)

**Comment by LaurensRietveld** [comment]
The application cache mechanism is removed in the latest deployment (see https://yasgui.triply.cc)
