### ISSUE TITLE
Encode YASR map view fullscreen as part of the YASGUI link

### ISSUE THREAD

**Issue by l00mi** [TriplyDB/Yasgui#110]
E.g. this query resulting in a [map](https://test.lindas-data.ch/sparql-ui/#query=PREFIX+schema%3A+%3Chttp%3A%2F%2Fschema.org%2F%3E%0APREFIX+wgs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2003%2F01%2Fgeo%2Fwgs84_pos%23%3E%0APREFIX+geo%3A+%3Chttp%3A%2F%2Fwww.opengis.net%2Font%2Fgeosparql%23%3E%0APREFIX+rdfs%3A+%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0A%0ASELECT+*%0AWHERE+%7B+GRAPH+%3Fg+%7B%0A%0A%09%3Fs+a+schema%3APhotograph+%3B%0A++++%09+schema%3Adescription+%3Flabel%3B%0A+++++++%09+schema%3AthumbnailUrl+%3Fthumb%3B%0A++++++%09+schema%3Aimage+%3FimageLink%3B%0A+++++++++wgs%3Alat+%3Flat+%3B%0A+++++++++wgs%3Along+%3Flong+.%0A+++++++++%0A++++++BIND(STRDT(CONCAT(%22POINT(%22%2C+STR(%3Flat)%2C+%22+%22%2C+STR(%3Flong)%2C+%22)%22)%2C+geo%3AwktLiteral)+AS+%3Fstationwkt).%0A++++BIND(+CONCAT(%22%3Cp%3E%22%2C+%3Flabel%2C+%22%3C%2Fp%3E%3Cp%3E%3Ca+href%3D'%22%2C+STR(%3FimageLink)%2C+%22'%3E%3Cimg+src%3D'%22%2C+STR(%3Fthumb)%2C+%22'%3E%3C%2Fa%3E%3C%2Fp%3E%22)+AS+%3FstationwktLabel).%0A%0A%7D%7D&contentTypeConstruct=text%2Fturtle&contentTypeSelect=application%2Fsparql-results%2Bjson&endpoint=https%3A%2F%2Ftest.lindas-data.ch%2Fsparql&requestMethod=POST&tabTitle=Query&headers=%7B%7D&outputFormat=leaflet) but where the YASR is fullscreen.

Use-case: To share to a non-technical audience.

**Comment by LaurensRietveld** [comment]
I agree that sharing SPARQL query results without bothering with the technicalities behind it is indeed an important feature. I'd consider it out of the scope of Yasgui, as with other tools such as data stories (https://triply.cc/products/stories and https://stories.triply.cc/) this is already possible
