### ISSUE TITLE
Disable editing of the endpoints's list text

### ISSUE THREAD

**Issue by mhabsaoui** [TriplyDB/Yasgui#115]
Hi,
I would like to disable the Edit state of the endpoints listbox (from Js or CSS) so the user cannot modify the Endpoint text value. 

Is it already provided on yasgui api ?

**Comment by LaurensRietveld** [comment]
Nope, you can completely disable the listbox via CSS, or keep it enabled, but nothing in between. Open to a PR if you've got one though
