### ISSUE TITLE
Query results are not displayed if the user switches tab during loading

### ISSUE THREAD

**Issue by exaexa** [TriplyDB/Yasgui#119]
If the user switches tabs during loading of a query, the results are not displayed in the view of YASR. Switching to some other view and back (e.g. "Pivot Table" and back to "Table") fixes the view. AFAIK the YASR view is not updated if it either does not exist or is hidden.

I haven't had time to dig into the exact reason yet (I will), so I'm opening this issue for tracking and in a hope that someone knowledgeable about YASGUI internals will possibly find an easy fix much earlier than me. :]

**Comment by wouterbeek** [comment]
@exaexa Thanks for looking into this, it's been a long-standing annoyance to me as well.

**Comment by LaurensRietveld** [comment]
This is fixed in the latest release  (see https://github.com/TriplyDB/Yasgui and https://yasgui.triply.cc)
