### ISSUE TITLE
Look into potential security vulnerability

### ISSUE THREAD

**Issue by wouterbeek** [TriplyDB/Yasgui#120]
Github found the following potential security vulnerability:

> The jquery-ui dependency defined in package-lock.json has a known moderate severity security vulnerability in version range < 1.12.0 and should be updated.

**Comment by LaurensRietveld** [comment]
Jep, I know. Nothing to be done about it for the current version, as upping jquery uit causes problems with other jquery plugins. Pushing this forward to the next rewrite, as that one won't contain jquery

**Comment by LaurensRietveld** [comment]
The latest version is mostly up-to-date with all dependencies
