### ISSUE TITLE
Option to disable proxy

### ISSUE THREAD

**Issue by bjonnh** [TriplyDB/Yasgui#130]
I have an endpoint on a docker container (nginx that add cors): 
http://172.21.0.4:8080

it turns out that yasgui.org fails because it tries to reach it with /proxy/ 
in the console:
XML Parsing Error: no root element found
Location: https://yasgui.org/proxy/
Line Number 1, Column 1:

**Comment by LaurensRietveld** [comment]
When drawing yasgui, or when changing the selected endpoint, Yasgui:
- Issues a simple `ask` query to the endpoint
- If the endpoint returns a (2xx,3xx,4xx or 5xx) response, it'll query the endpoint directly. 
- If there is no response and status code to be read, it'll assume there are cors issues, and it'll use the proxy

If this is still an issue for you, could you elaborate on what stage of the above steps fail?
