### ISSUE TITLE
Typeahead hinter support

### ISSUE THREAD

**Issue by lewismc** [TriplyDB/Yasgui#131]
One of the major problems we have is users knowing how to navigate the constituent parts of our datasets e.g. knowing to type for example `ogc:asWKT` as a predicate to link to a specific geometry literal. 
It would be super handy if we could implement typeahead hinter support similar as to what is done over at [graphiql](http://graphql.org/swapi-graphql).
Is there any motivation to work on this functionality? It would really help our users.

**Comment by lewismc** [comment]
Ah ha, I see this available here https://github.com/scampi/gosparqled

**Comment by LaurensRietveld** [comment]
Indeed, gosparqled supports functionality such as this. Yasgui supports adding custom autocompleters (see https://github.com/TriplyDB/Yasgui/tree/master/packages/yasqe/src/autocompleters), so if you have an API that provides fast autocompletion suggestions, it should be straight forward to include that in Yasgui
