### ISSUE TITLE
How to set configurations when object initalized

### ISSUE THREAD

**Issue by shawnhind** [TriplyDB/Yasgui#143]
We're using YASGUI to query our graph database and our query endpoint uses a CSRF token for session validation.  

I'm initializing YASGUI doing this:

```javascript
const yasgui = new Yasgui(document.getElementById("yasgui"), {
                requestConfig: { 
                    endpoint: "{{ route('sparql.query') }}", 
                    headers: {
                        "X-CSRF-TOKEN": someCsrfToken
                    }
                },
                copyEndpointOnNewTab: false  
            });
```

However after logging out and logging back in and then reloading the page, YASGUI is still sending the original header with the expired CSRF token which I assume it's getting from the cached config in local storage.

How can I modify config values in a way that will override the saved local storage values.  Is there a way other than to run code that will clear the local storage object?

**Comment by LaurensRietveld** [comment]
I've changed the request configuration setup somewhat. 

- All fields in the request configuration support a getter function
- These are not persistent to local storage (it's a function)
- They are merged (when possible) with user-provided values the user enters in the tab settings pane

Something like this should work now (when using the latest release):

```javascript
const yasgui = new Yasgui(document.getElementById("yasgui"), {
                requestConfig: { 
                    endpoint: "{{ route('sparql.query') }}", 
                    headers: () => ({
                        "X-CSRF-TOKEN": someCsrfToken
                    })
                },
                copyEndpointOnNewTab: false  
            });
```

**Comment by shawnhind** [comment]
Great, thanks.  I'll give this a try later today.

**Comment by shawnhind** [comment]
@LaurensRietveld this worked perfectly, thanks.

**Comment by LaurensRietveld** [comment]
Great :+1:
