### ISSUE TITLE
ideas to improve endpoint selector

### ISSUE THREAD

**Issue by JJ-Author** [TriplyDB/Yasgui#148]
Hi I would like to propose two ideas for the endpoint selector.

First I think it would be useful to include a button "show more" or "see all" when the endpoint selector is clicked. It took a while for me to understand that you are performing a search and why the other endpoints I configured did not show up. I assume non-pro users might struggle with this as well.

Second it would be good to include the labels or description as in yasgui 2 again.

**Comment by LaurensRietveld** [comment]
Good to know about this UX issue, thanks. About the labels +  descriptions. This is possible when configuring Yasgui yourself, see https://triply.cc/docs/yasgui-api#yasgui-config . Does that solution suffice?

**Comment by JJ-Author** [comment]
Hi @LaurensRietveld, ah ok I see that I missed the explanation in the comment.  I configured the endpoints like this for Yasgui v4 at the moment

```
        Yasgui.defaults.endpointCatalogueOptions.getData = () => {
            return [{
                endpoint: "https://databus.dbpedia.org/repo/sparql",
                title: "Databus DFP"
            }, {
                endpoint: "https://databus.dbpedia.org/testrepo/sparql",
                title: "Databus TEST DFP"
            }, {
                endpoint: "https://dbpedia.org/sparql",
                title: "English DBpedia"
            }]
        };

```
Yasgui v2 used to show the label in the endpoint selector. I did not find an example how this works for v4 in the docu you mentioned. I mean this is a really just a nice to have thing - nothing important.

**Comment by LaurensRietveld** [comment]
In v4 you'll have to draw the html element yourself using the `renderItem` field. We changed this behaviour, as it allows for better customizability (e.g. you can only show the label and hide the endpoint. Or, you can add other html elements like images)

See below for something that would match your usecase (untested btw):

```
Yasgui.defaults.endpointCatalogueOptions.renderItem: (data, source) => {
	const contentDiv = document.createElement("div");
	if (data.value.title) {
	
		const header = document.createElement('h4');
		header.innerText = header.data.value.title;
		contentDiv.appendChild(header);
	}
	const endpoint = document.createElement('span');
	endpoint.innerText = data.value.endpoint;
	contentDiv.appendchild(endpoint);
	source.appendChild(contentDiv);
}
```

**Comment by JJ-Author** [comment]
Ok cool, thank you. This worked out.
```
Yasgui.defaults.endpointCatalogueOptions.renderItem = (data, source) => {
                const contentDiv = document.createElement("div");
                if (data.value.title) {
                                
                                        const header = document.createElement('h4');
                                        header.innerText = data.value.title;
                                        contentDiv.appendChild(header);
                                }
                const endpoint = document.createElement('span');
                endpoint.innerText = data.value.endpoint;
                contentDiv.appendChild(endpoint);
                source.appendChild(contentDiv);
};
```
Might potentially be useful to add this to the docu.

**Comment by LaurensRietveld** [comment]
great :+1:
