### ISSUE TITLE
Configuring the list "catalogueEndpoints" in current Yasui Version

### ISSUE THREAD

**Issue by gpetz** [TriplyDB/Yasgui#149]
As explained in https://github.com/TriplyDB/Yasgui/issues/114, is there still support of YASGUI.defaults.catalogueEndpoints in the current version of Yasgui?

**Comment by LaurensRietveld** [comment]
There is. There was already documentation (see https://triply.cc/docs/yasgui-api#yasgui-config). Extended it with a bit of text on how to change the rendering of the suggestions

**Comment by gpetz** [comment]
Thanx, but the endpointCatalogueOptions are not working for me. Am I missing something?

```
const yasgui = new Yasgui(document.getElementById("yasgui"), {
    requestConfig: {
        endpoint: "http://example.com/sparql1"
    },
    copyEndpointOnNewTab: false,
    endpointCatalogueOptions: {
        getData: () => {
            return [{
                    endpoint: "http://example.com/sparql1"
                },
                {
                    endpoint: "http://example.com/sparql2"
                }
            ];
        }
    }
});
```

![grafik](https://user-images.githubusercontent.com/455986/74152139-ee07dd00-4c0d-11ea-8b8f-3eaea2106660.png)

**Comment by LaurensRietveld** [comment]
You stumbled across the UX issue from #148. The search field is a filter. I.e., to see all suggestions, remove the currently selected endpoint and you should see them
