### ISSUE TITLE
Prefix not completed in BIND scope

### ISSUE THREAD

**Issue by selevt** [TriplyDB/Yasgui#156]
Can be reproduced on [demo system](https://yasgui.triply.cc/#query=SELECT%20*%20WHERE%20%7B%0A%20%20BIND(rdf%3Atype%20as%20%3Fx)%0A%7D%20LIMIT%2010&endpoint=https%3A%2F%2Fdbpedia.org%2Fsparql&requestMethod=POST&tabTitle=Query&headers=%7B%7D&contentTypeConstruct=text%2Fturtle%2C*%2F*%3Bq%3D0.9&contentTypeSelect=application%2Fsparql-results%2Bjson%2C*%2F*%3Bq%3D0.9&outputFormat=table).

When typing something like `?x rdf:type ?y`, the `PREFIX rdf` is automatically added.
This doesn't work withing a BIND statement, e.g. `BIND(rdf:type as ?x)`, which results in a shown error `Prefix 'rdf' is not defined.`

**Comment by GerwinBosch** [comment]
Hi,

#157 Will fix your problem. 
The prefix will now be autocompleted and added to the query.
