### ISSUE TITLE
CollapsePrefixesOnLoad not acted upon

### ISSUE THREAD

**Issue by woutermont** [TriplyDB/Yasgui#164]
While working on #162 I noticed prefixes are also not collapsed when `Yasgui.Yasqe.defaults.collapsePrefixesOnLoad` is set to `true`.

**To reproduce**:
```
<div id="yasgui"></div>
<script>

   Yasgui.Yasqe.defaults.collapsePrefixesOnLoad = true;
   Yasgui.Yasqe.defaults.value = 
      "PREFIX one: <https://example.org/one/>" + "\n" +
      "PREFIX two: <https://example.org/two/>";
   
   const yasgui = new Yasgui(document.getElementById("yasgui"));

   //yasgui.getTab().yasqe.collapsePrefixes();

</script>
```
Only when also uncommenting the per-tab function call, the prefixes are collapsed.

I post this as an issue since I'm not sure where this default should be read.

**Comment by LaurensRietveld** [comment]
Thanks for the report, this is now fixed :+1:
