### ISSUE TITLE
Autocompletion does not work 

### ISSUE THREAD

**Issue by seme4ki** [TriplyDB/Yasgui#173]
Hi there!
Somehow I have the issue that the autocompletion of the YASGUI live demo does not work (yasgui.triply.cc). Whenever I type in a prefix and a colon, it says "Press Crt+Spacebar to autocomplete". Then it says "Failed fetching suggestions". In the network tab of the developer's toolbar the following error(s) appear:

- `Access to XMLHttpRequest at 'https://lov.linkeddata.es/dataset/lov/api/v2/autocomplete/terms?q=http%3A%2F%2Fdbpedia.org%2Fontology%2Fab&page_size=50&type=property' from origin 'https://yasgui.triply.cc' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`
- `yasgui-pro.min.js:6 GET https://lov.linkeddata.es/dataset/lov/api/v2/autocomplete/terms?q=http%3A%2F%2Fdbpedia.org%2Fontology%2Fab&page_size=50&type=property net::ERR_FAILED`

What can I do to solve this issue? I tested it with the wikidata endpoint as well as with the dbPedia endpoint. 

Thanks in advance!

**Comment by GerwinBosch** [comment]
Hello @seme4ki 

We use the API from [LOV](lov.linkeddata.es) to retrieve auto-completion suggestions. They seem to have some issues with their server at the moment (503's) for me. As this API is out of our hands we can't do much at the moment except to wait until their services are up again. (Or find a different autocomplete service)

I hope I have informed you enough!

**Comment by GerwinBosch** [comment]
The LOV servers are up again, closing this issue
