### ISSUE TITLE
npm/yarn install error

### ISSUE THREAD

**Issue by shinysong** [TriplyDB/Yasgui#187]
Hello.
I am new to yasgui.

I installed it with npm referring to the official website.

However, the file path is strange and there are some errors.

I think there is no connection with this repository.

It was confirmed that the version was upgraded to 4.2.18 on 2021-09-28.

Maybe there's an error because you're still upgrading?

Or is my local computer the problem? Or i don't understand installing Yasgui?
![화면 캡처 2021-09-29 012021](https://user-images.githubusercontent.com/51478604/135126547-4e7bee58-33db-4030-8b78-73256fabc5b1.jpg)

**Comment by GerwinBosch** [comment]
Hello @shinysong thanks for trying out YASGUI,

We had some issues with our CI releasing this particular version. The newest version should have the correct configuration.

I can't discover anything strange based on the file structure

Could you go a bit further in detail how the file path is strange and what kind of yarn/npm errors you get?

**Comment by shinysong** [comment]
Thank you for your kind answer. @GerwinBosch 

First, my goal is to connect the blazegraph endpoint and yasgui.

So, I installed yasgui and expected a screenshot(Overview of Yasgui Components) of [Yasgui API Reference](https://triply.cc/docs/yasgui-api#yasqe-api). However, my local  node_modules/@tripley/yasgui/yasgui.html was the same as the picture below.

![yasgui-html](https://user-images.githubusercontent.com/51478604/135231216-f8c95925-ab74-4588-a054-5663365342a4.jpg)

And, I tried to find yasgui.config guided by https://triply.cc/docs/yasgui-api#yasgui-config,
I don't know if I have to write it myself or if there are .config and .defaluts exist where packages.

I would appreciate it if you could tell me where to write it when writing it myself.

I'm sorry for the lack of basic knowledge because it's my first time doing this.

**Comment by GerwinBosch** [comment]
Ah as Yasgui is a package its intended to be integrated into other (javascript) projects. The easiest way to configure your own instance of yasgui is by using the CDN approach

Create a HTML file and retrieve Yasgui with a cdn as documented [here](https://triply.cc/docs/yasgui-api#web).
You can change the config using the third snippet

**Comment by shinysong** [comment]
Thank you for a detailed description :)

**Comment by GerwinBosch** [comment]
Welcome back @shinysong

Any reason to re-open this issue? Can we provide any further assistance?

**Comment by shinysong** [comment]
sorry, my mistake!
