### ISSUE TITLE
How to use Pivot Plugin

### ISSUE THREAD

**Issue by ajberasategui** [TriplyDB/Yasgui#198]
[HELP WANTED] 

Hello. I'm currently working on a project and we were planning to use Yasgui on it. 
I spent some time trying the npm version but we would like to leverage the pivot plugin.

After going through your docs my understanding is that pivot plugin was present in the deprecated version of yasgui but it's not in the current version. I couldn't find any docs on how to install it and now I'm curious if that's even possible.

Any help is very much appreciated.

**Comment by GerwinBosch** [comment]
Hello and sorry for the confusion, [we've just updated](https://github.com/TriplyDB/Documentation/commit/09dfe0d59d946dbabbd552e4b4246d916fdce465) our documentation about the difference between the base plugins and the [additional plugins](https://triply.cc/docs/yasgui-api#triplyDbPlugins). 

The plugin is still available on [yasgui.triply.cc](https://yasgui.triply.cc) or within [TriplyDB](https://triplydb.com/)

**Comment by ajberasategui** [comment]
Thank you very much for the clarification.

Best regards.
