### ISSUE TITLE
setting queryingDisabled after config is set

### ISSUE THREAD

**Issue by eric-personal** [TriplyDB/Yasgui#204]
Is there a way to set queryingDisabled after Yasgui instantiation. 
I'm looking for a way to disable submit of query while the query response is waiting to be returned. 
I tried to reset the queryingDisabled property example: 

`yasgui.config.yasqe.queryingDisabled = true;`

The only way the above line seems to work is durning Yasgui instantiation. 

I know I can set pointer-events: none; on the container element but anyone can turn this back on via dev tools. I'm trying to prevent multiple calls to the submit query until the first submit was successful. 

thanks!

**Comment by GerwinBosch** [comment]
Hello @eric-personal,

One possible way of doing this is using Yasqe's event system:

```ts
yasgui.on("query", (_yasgui,tab) => tab.yasqe.config.queryingDisabled=true);
yasgui.on("queryResponse", (_yasgui,tab) => {
  tab.yasqe.config.queryingDisabled=false;
  tab.yasqe.drawButtons();
});
```

**Comment by GerwinBosch** [comment]
I am closing this issue as I interpret the emoji's to mean that the issue is resolved

**Comment by eric-personal** [comment]
Yes thank you your solution was perfect.
