### ISSUE TITLE
there is any way to assign my api response to Yasr

### ISSUE THREAD

**Issue by shanu3742** [TriplyDB/Yasgui#208]
> i get  response from  sparqul  by using simple API call but now I want to pass my response to yasr and show that on webpage is there any way to assign my response to Yasr component in react

**Comment by GerwinBosch** [comment]
Hello @shanu3742,

You can do this by assigning YASR to a ref object and call `yasrRef.current.setResponse`

Let me know if this helps. Have a nice day!

**Comment by shanu3742** [comment]
Hi @GerwinBosch  i'm getting error like **ncaught TypeError: yasrRef.current.setResponse is not a function**

**Comment by GerwinBosch** [comment]
@shanu3742 I meant to put the instance of YASR in the ref when it is being initialized

**Comment by shanu3742** [comment]
Now I'm getting result in the form of rawResponse  but not in table from is any other things i have to do for that

**Comment by GerwinBosch** [comment]
I'm going to guess that you get back some kind of "normal" JSON. Make sure to add an accept header to your request. Use:  `application/sparql-results+json` (preferred), `application/sparql-results+xml`, CSV or TSV for Select queries and any kind of serialized triple format for construct queries

**Comment by shanu3742** [comment]
hi @GerwinBosch  sorry for all the basic question  and giving your valuable time , will you help me one more time how can I add other plugin like   'pivot','gchart' etc

**Comment by GerwinBosch** [comment]
Unfortunately, those are only available on [yasgui.triply.cc](//yasgui.triply.cc) and within [TriplyDB](https://triplydb.com/) see https://triply.cc/docs/yasgui-api#triplyDbPlugins

You can however write your own using https://triply.cc/docs/yasgui-api#writing-a-yasr-plugin

**Comment by srinivasAarth** [comment]
hi @GerwinBosch is there any way to disable the editing option in yasqe(query editor) I just want to show the query, not like interactive query edition
I'm custom selecting variables, query properties, and relations  from the input select fields so, I don't want the option like editing query on yasqe pannel

**Comment by GerwinBosch** [comment]
@srinivasAarth you can do that by setting `readOnly:false`

**Comment by srinivasAarth** [comment]
@GerwinBosch thanks for the response its working fine as like what I expected after adding the `readOnly:true` property

**Comment by GerwinBosch** [comment]
Oops got the boolean value wrong 😅. However, since your issues seem to be resolved can this issue be closed?

**Comment by srinivasAarth** [comment]
yes @GerwinBosch it was closed
